
  CREATE TABLE "TB_BLUE_MEM_INFO" 
   (	"MEM_SEQ" NUMBER(10,0) NOT NULL ENABLE, 
	"MEM_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"MEM_PWD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"MEM_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"MEM_GND" VARCHAR2(1 BYTE), 
	"MEM_BIRTH" VARCHAR2(10 BYTE), 
	"MEM_TEL" VARCHAR2(13 BYTE), 
	"MEM_EMAIL" VARCHAR2(50 BYTE), 
	"MEM_ADDR" VARCHAR2(100 BYTE), 
	"MEM_USE_YN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"INS_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"INS_DT" DATE DEFAULT SYSDATE, 
	"UPD_ID" VARCHAR2(50 BYTE), 
	"UPD_DT" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("MEM_SEQ", "MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------

  CREATE TABLE "TB_BLUE_BRD_MAIN" 
   (	"BRD_SEQ" NUMBER(10,0) NOT NULL ENABLE, 
	"BRD_FLAG" VARCHAR2(1 BYTE) DEFAULT 'B', 
	"BRD_SUBJECT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BRD_CONTENT" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"BRD_HITS" NUMBER(10,0) DEFAULT 0, 
	"BRD_DEL_YN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"BRD_WRT_NAME" VARCHAR2(50 BYTE), 
	"BRD_PWD" VARCHAR2(50 BYTE), 
	"INS_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"INS_DT" DATE DEFAULT SYSDATE, 
	"UPD_ID" VARCHAR2(50 BYTE), 
	"UPD_DT" DATE DEFAULT SYSDATE, 
	"BRD_WRT_NICK" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("BRD_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------

  CREATE TABLE "TBL_EMP" 
   (	"NO" NUMBER(11,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE), 
	"JOB" VARCHAR2(50 BYTE), 
	"DEPT" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------

  CREATE TABLE "SAMPLE" 
   (	"ID" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"USE_YN" CHAR(1 BYTE), 
	"REG_USER" VARCHAR2(10 BYTE), 
	 PRIMARY KEY ("ID")
   ) ;

--------------------------------------------------------

  CREATE TABLE "IDS" 
   (	"TABLE_NAME" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"NEXT_ID" NUMBER(30,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("TABLE_NAME")
   ) ;

--------------------------------------------------------

INSERT INTO TB_BLUE_MEM_INFO
		(
			  MEM_SEQ
			, MEM_ID
			, MEM_PWD
			, MEM_NAME
			, MEM_GND
			, MEM_BIRTH
			, MEM_TEL
			, MEM_EMAIL
			, MEM_ADDR
			, MEM_USE_YN
			, INS_ID
			, INS_DT
			, UPD_ID
			, UPD_DT
		) VALUES ( 
			 1
          	, 'admin'
          	, '11111'
          	, '관리자'
          	, 'M'
          	, '20220301'
          	, '010-1111-2222'
          	, 'aaaa@aaaa.com'
          	, '경기도'
          	, 'Y'
          	, 'admin'
          	, SYSDATE
          	, 'admin'
          	, SYSDATE
		);

INSERT INTO TBL_EMP
VALUES(1,'홍길동','대리','영업');

INSERT INTO IDS(TABLE_NAME, NEXT_ID)
VALUES ('SAMPLE', 1);

INSERT INTO SAMPLE (ID, NAME, DESCRIPTION, USE_YN, REG_USER )
VALUES ( 'SAMPLE-00001','홍길동','경력','Y','ADMIN');

--------------------------------------------------------

COMMIT;



